import 'dart:convert';

/// Complete weekly aggregation snapshot spanning all Cadence domains.
class WeeklySummaryData {
  final DateTime weekStartDate;
  final DateTime weekEndDate;
  final int compositeScore;
  final int focusScore;
  final int movementScore;
  final int budgetScore;
  final int routineScore;

  // Raw domain metrics
  final int totalFocusSeconds;
  final int focusSessionsCount;
  final String topSubject;
  final int totalSteps;
  final double totalDistanceKm;
  final double totalExpenses;
  final double weeklyBudget;
  final int routineCompletedCount;
  final int routinePossibleCount;

  const WeeklySummaryData({
    required this.weekStartDate,
    required this.weekEndDate,
    required this.compositeScore,
    required this.focusScore,
    required this.movementScore,
    required this.budgetScore,
    required this.routineScore,
    required this.totalFocusSeconds,
    required this.focusSessionsCount,
    required this.topSubject,
    required this.totalSteps,
    required this.totalDistanceKm,
    required this.totalExpenses,
    required this.weeklyBudget,
    required this.routineCompletedCount,
    required this.routinePossibleCount,
  });

  /// Formatted focus time (e.g. "14h 25m").
  String get formattedFocusTime {
    final hours = totalFocusSeconds ~/ 3600;
    final mins = (totalFocusSeconds % 3600) ~/ 60;
    if (hours == 0) return '${mins}m';
    return '${hours}h ${mins}m';
  }

  /// Routine adherence percentage (0-100).
  int get routinePercentage {
    if (routinePossibleCount == 0) return 100;
    return ((routineCompletedCount / routinePossibleCount) * 100).round().clamp(0, 100);
  }

  /// Human-friendly week date range label.
  String get dateRangeLabel {
    final startStr = '${_monthName(weekStartDate.month)} ${weekStartDate.day}';
    final endStr = '${_monthName(weekEndDate.month)} ${weekEndDate.day}, ${weekEndDate.year}';
    return '$startStr – $endStr';
  }

  static String _monthName(int month) {
    const months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ];
    return months[month - 1];
  }

  /// Exports a structured Markdown report suitable for Obsidian, Notion, or personal logs.
  String toMarkdownReport({String? reflectionNotes}) {
    final buffer = StringBuffer();
    buffer.writeln('# 📅 Weekly Review: $dateRangeLabel');
    buffer.writeln();
    buffer.writeln('**Life Rhythm Score:** $compositeScore / 100');
    buffer.writeln();
    buffer.writeln('## 📊 Domain Performance');
    buffer.writeln('- **🧠 Focus & Study**: $focusScore% ($formattedFocusTime across $focusSessionsCount sessions; Top: $topSubject)');
    buffer.writeln('- **🏃 Movement & Health**: $movementScore% (${totalSteps.toString()} steps, ${totalDistanceKm.toStringAsFixed(1)} km)');
    buffer.writeln('- **💳 Financial Health**: $budgetScore% (\$${totalExpenses.toStringAsFixed(2)} spent / \$${weeklyBudget.toStringAsFixed(2)} weekly allocation)');
    buffer.writeln('- **✅ Daily Routines**: $routineScore% ($routineCompletedCount / $routinePossibleCount items completed)');
    buffer.writeln();
    if (reflectionNotes != null && reflectionNotes.trim().isNotEmpty) {
      buffer.writeln('## ✍️ Weekly Reflection');
      buffer.writeln(reflectionNotes.trim());
      buffer.writeln();
    }
    buffer.writeln('---');
    buffer.writeln('*Generated by Cadence Personal OS on ${DateTime.now().toIso8601String().split('T').first}*');
    return buffer.toString();
  }

  Map<String, dynamic> toJson() {
    return {
      'weekStartDate': weekStartDate.toIso8601String(),
      'weekEndDate': weekEndDate.toIso8601String(),
      'compositeScore': compositeScore,
      'focusScore': focusScore,
      'movementScore': movementScore,
      'budgetScore': budgetScore,
      'routineScore': routineScore,
      'totalFocusSeconds': totalFocusSeconds,
      'focusSessionsCount': focusSessionsCount,
      'topSubject': topSubject,
      'totalSteps': totalSteps,
      'totalDistanceKm': totalDistanceKm,
      'totalExpenses': totalExpenses,
      'weeklyBudget': weeklyBudget,
      'routineCompletedCount': routineCompletedCount,
      'routinePossibleCount': routinePossibleCount,
    };
  }

  factory WeeklySummaryData.fromJson(Map<String, dynamic> json) {
    return WeeklySummaryData(
      weekStartDate: DateTime.parse(json['weekStartDate'] as String),
      weekEndDate: DateTime.parse(json['weekEndDate'] as String),
      compositeScore: json['compositeScore'] as int,
      focusScore: json['focusScore'] as int,
      movementScore: json['movementScore'] as int,
      budgetScore: json['budgetScore'] as int,
      routineScore: json['routineScore'] as int,
      totalFocusSeconds: json['totalFocusSeconds'] as int? ?? 0,
      focusSessionsCount: json['focusSessionsCount'] as int? ?? 0,
      topSubject: json['topSubject'] as String? ?? 'None',
      totalSteps: json['totalSteps'] as int? ?? 0,
      totalDistanceKm: (json['totalDistanceKm'] as num?)?.toDouble() ?? 0.0,
      totalExpenses: (json['totalExpenses'] as num?)?.toDouble() ?? 0.0,
      weeklyBudget: (json['weeklyBudget'] as num?)?.toDouble() ?? 0.0,
      routineCompletedCount: json['routineCompletedCount'] as int? ?? 0,
      routinePossibleCount: json['routinePossibleCount'] as int? ?? 0,
    );
  }

  String toJsonString() => jsonEncode(toJson());

  factory WeeklySummaryData.fromJsonString(String str) =>
      WeeklySummaryData.fromJson(jsonDecode(str) as Map<String, dynamic>);
}
